apiVersion: route.openshift.io/v1                                         
kind: Route                                                               
metadata:                                                                 
  name: martin-argo                                                       
  labels:                                                                 
    app: martin-argo                                                      
spec:                                                                     
  to:                                                                     
    kind: Service                                                         
    name: martin-argo                                                     
    weight: 100
